general:
  use_uvloop: true

llms:
  nim_llm:
    _type: nim
    model_name: meta/llama-3.1-70b-instruct
    temperature: 0.0
    max_tokens: 250
  r1_model:
    _type: nim
    model_name: deepseek-ai/deepseek-r1
    temperature: 0.0
    max_tokens: 2000

functions:
  poem_documents:
    _type: text_file_ingest
    ingest_glob: MyPersonalizedAgent/poem_data/*.txt
    description: "Search for information about Poems. For any questions about poems in English and Chinese, you must use this tool!"
    embedder_name: nv-embedqa-e5-v5
    chunk_size: 512

  poem_agent:
    _type: tool_calling_agent
    tool_names: [poem_documents]
    llm_name: nim_llm
    verbose: true
    handle_parsing_errors: true
    max_retries: 2

embedders:
  nv-embedqa-e5-v5:
    _type: nim
    model_name: nvidia/nv-embedqa-e5-v5

workflow:
  _type: reasoning_agent
  llm_name: r1_model
  augmented_fn: poem_agent
  verbose: true

  instruction_prompt_template: |
    Answer the following question based on message history: {input_text} 
    Here is a plan for execution that you could use to guide you: {reasoning_output}
    NOTE: Remember to follow your guidance on how to format output, etc.
    You must respond in the same language as the question that may need translation from English to Chinese or from Chinese to English.